### ISSUE TITLE
Auto Accept

### ISSUE THREAD

**Issue by DoisPontinhos** [orteney/champmastery#2]
Auto accept doesn't seem to work

Also would like to see a way to save my own runes and item builds to the app

**Comment by orteney** [comment]
Yeah there is issue with subscribing to machmaking event :< It's 100% working after launching app during machmaking button...

Implementing own runes and builds are not in my scope of interest for this app

**Comment by orteney** [comment]
With the update [3.7.1](https://github.com/orteney/sebastian/releases/tag/3.7.1) you should once activate AutoAccept toggle during match accept button appears and it's going to work as inteded :з
