### ISSUE TITLE
Bug Report: 404 Error When Attempting Champion Selection

### ISSUE THREAD

**Issue by Ku-Tadao** [orteney/champmastery#4]
### Description
Receiving a 404 (Not Found) error when attempting to select a champion. The error indicates a missing warehouse resource.

### Steps to Reproduce
1. Open sebastian application
2. Navigate to champion selection
3. Attempt to pick a champion
4. Error occurs instead of champion selection

### Error Message
Exception: [{code: not_found, details: {api_name: http_shared, http_code: 404, response: {data: {body: {"error_code":"NOT_FOUND","message":"The warehouse ecd027b845bd6a92 was not found."}...}}}]
![image](https://github.com/user-attachments/assets/e7536d10-d237-46b9-8db8-31cb272aa6f8)

### Technical Details
- Warehouse ID: ecd027b845bd6a92
- Queue ID: 420
- Build tier: Standard
- Individual position: TOP

### Additional Notes
- Error occurs consistently on champion selection
- The error references a missing warehouse resource
- Full error trace included above for debugging purposes

### Expected Behavior
Should be able to select a champion without encountering a database/warehouse error.

**Comment by orteney** [comment]
Thanks for your report! 
I pushed a new version [4.4.2](https://github.com/orteney/sebastian/releases/tag/4.4.2) with fixes for this issue
